title: LET'S GROW YOUR BUSINESS
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: >-
  Improve your business performance, exceed your aspirations, build exceptional
  value
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#58585A'
    - '#D82027'
    - '#000000'
    - '#BF0000'
    - '#FF0000'
  lightness: 0.08395522
navigation:
  - name: Services
    id: 025e5c4c-93da-4f57-8da9-470eb950da66
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3ebda1d3-9ad8-45bc-94d0-d2f9425d62f3.png
author:
  name: Dan Egerton
  email: Dan@actus.consulting
name: Actus Consulting
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd935c5a-2847-4246-99bb-44568a3f5935.png
typography_spectrum: 0.3614739
layout_spectrum: 0.5802239
