collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3914371123537421
  brandStrength: 0.1034875784534961
  lightness: 0.9227734529413283
  brandColors:
    - '#642D92'
    - '#25184D'
    - '#CBD7EF'
    - '#9CB1DA'
    - '#5A8FB3'
  rhythmicContrast: 0.8037661663256586
typography_spectrum: 0.8978545
layout_spectrum: 0
name: Actus Consulting
